version: '3.8'

services:
  resume:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: appResume
    image: oekeur/resume:latest
    ports:
      - "3000"
    env_file:
      - .env

networks:
  default:
    external:
      name: proxy