import Head from "next/head";
import styles from "../styles/Home.module.css";
import layout from "../styles/layout.module.scss";
import NavBar from "../components/NavBar/NavBar";
import { Box, Container, Heading } from "react-bulma-components";
import IntroCard from "../components/IntroCard/introCard";
import TagGroup from "../components/TagGroup/TagGroup";
import { useAppContext } from "../context/state";
import Languages from "../components/Languages/Languages";

export default function Home() {
  const data = useAppContext();
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Resume | Oscar Keur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <Container className={styles.container}>
        <main className={styles.main}>
          <IntroCard />
          <Box className={layout.fullWidth}>
          <Languages data={data.languages} />
          <Box>
            <Heading>Interests</Heading>
            <Heading subtitle={true}>Personal</Heading>
            <TagGroup data={data.interests.personal} />
            <Heading subtitle={true}>Professional</Heading>
            <TagGroup data={data.interests.professional} />
          </Box>
        </main>
      </Container>
    </div>
  );
}
