import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import data from "../data/resume.json";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Resume | Oscar Keur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>About me: Oscar Keur</h1>
      </main>
    </div>
  );
}
