import Head from "next/head";
import styles from "../styles/Home.module.css";
import data from "../data/resume.json";
import NavBar from "../components/nav/navbar";
import {
  Box,
  Container,
  Content,
  Heading,
  Media,
  Tag,
} from "react-bulma-components";
import profilePic from "../public/photo.jpg";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Resume | Oscar Keur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <Container className={styles.container}>
        <main className={styles.main}>
          <Box>
            <Media>
              <Media.Item align="left">
                <Image
                  src={profilePic}
                  alt="Picture of the author"
                  width={200}
                  height={264}
                  layout="intrinsic"
                  placeholder="blur"
                />
              </Media.Item>
              <Media.Item>
                <Content>
                  <Heading tooltip="he / him">Intro: Oscar Keur</Heading>
                  <Tag>he / him</Tag>
                  <Tag.Group>
                    {data.basics.competences.map((element, index) => {
                      return (
                        <Tag key={index} size="medium">
                          {element}
                        </Tag>
                      );
                    })}
                  </Tag.Group>
                </Content>
              </Media.Item>
            </Media>
          </Box>
        </main>
      </Container>
    </div>
  );
}
